name: Build Hugo With Cache
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check out the code from https://github.com/gohugoio/hugo.git
        uses: actions/checkout@v2
        with:
          repository: gohugoio/hugo
          ref: stable

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build the hugo executable
        run: go install --tags extended
        
        
      - name: Look for hugo exe
        run: find ~/go
